using Newtonsoft.Json;

namespace AssetRipper.Tools.AssetDumper.Models.Facts;

/// <summary>
/// Type Member Record (Type Members Domain)
/// Exports detailed metadata of type members such as fields, properties, methods, etc.
/// </summary>
public class TypeMemberRecord
{
	/// <summary>
	/// Domain is fixed to "type_members"
	/// </summary>
	[JsonProperty("domain")]
	public string Domain { get; set; } = "type_members";

	/// <summary>
	/// Primary key: Composite key ASSEMBLY::NAMESPACE::TYPENAME::MEMBERNAME (using :: to avoid conflicts)
	/// Example: "Assembly-CSharp::Game.Controllers::PlayerController::currentHealth"
	/// </summary>
	[JsonProperty("pk")]
	public string Pk { get; set; } = string.Empty;

	/// <summary>
	/// Assembly GUID (16 hexadecimal characters, links to assemblies.pk)
	/// Source: FNV1a.ComputeHash(AssemblyDefinition.FullName)
	/// </summary>
	[JsonProperty("assemblyGuid")]
	public string AssemblyGuid { get; set; } = string.Empty;

	/// <summary>
	/// Fully qualified name of the owning type
	/// Source: TypeDefinition.FullName
	/// </summary>
	[JsonProperty("typeFullName")]
	public string TypeFullName { get; set; } = string.Empty;

	/// <summary>
	/// Member name
	/// Source: FieldDefinition.Name / PropertyDefinition.Name / MethodDefinition.Name
	/// </summary>
	[JsonProperty("memberName")]
	public string MemberName { get; set; } = string.Empty;

	/// <summary>
	/// Member kind: field/property/method/event/constructor/nestedType
	/// Source: Concrete type of MemberReference
	/// </summary>
	[JsonProperty("memberKind")]
	public string MemberKind { get; set; } = string.Empty;

	/// <summary>
	/// Member type (field type, property type, or method return type)
	/// Source: FieldDefinition.FieldType.FullName / PropertyDefinition.PropertyType.FullName / MethodDefinition.ReturnType.FullName
	/// </summary>
	[JsonProperty("memberType")]
	public string MemberType { get; set; } = string.Empty;

	/// <summary>
	/// Visibility: public/internal/private/protected/protected internal/private protected
	/// Source: MemberDefinition.Attributes (parsed through GetVisibility method)
	/// </summary>
	[JsonProperty("visibility")]
	public string Visibility { get; set; } = string.Empty;

	/// <summary>
	/// Whether this is a static member
	/// Source: FieldDefinition.IsStatic / MethodDefinition.IsStatic / PropertyDefinition.GetMethod.IsStatic
	/// </summary>
	[JsonProperty("isStatic")]
	public bool IsStatic { get; set; }

	/// <summary>
	/// Whether Unity serializes this member
	/// Checks Unity serialization rules (public fields, [SerializeField], not [NonSerialized], supported types)
	/// </summary>
	[JsonProperty("serialized")]
	public bool Serialized { get; set; }

	/// <summary>
	/// Whether this is a virtual member (method/property)
	/// Source: MethodDefinition.IsVirtual
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isVirtual", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsVirtual { get; set; }

	/// <summary>
	/// Whether this overrides a base class member
	/// Source: MethodDefinition.IsReuseSlot && MethodDefinition.IsVirtual
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isOverride", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsOverride { get; set; }

	/// <summary>
	/// Whether this is a sealed member (prevents further overriding)
	/// Source: MethodDefinition.IsFinal
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isSealed", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsSealed { get; set; }

	/// <summary>
	/// Applied C# attributes (fully qualified names)
	/// Source: MemberDefinition.CustomAttributes
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
	public List<string>? Attributes { get; set; }

	/// <summary>
	/// XML documentation summary
	/// Source: DocumentationHandler / AssemblyParser.DocumentationString
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("documentationString", NullValueHandling = NullValueHandling.Ignore)]
	public string? DocumentationString { get; set; }

	/// <summary>
	/// Obsolete attribute message (if member is deprecated)
	/// Source: AssemblyParser.ObsoleteMessage / [Obsolete] attribute
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("obsoleteMessage", NullValueHandling = NullValueHandling.Ignore)]
	public string? ObsoleteMessage { get; set; }

	/// <summary>
	/// Unity native name
	/// Source: AssemblyParser.NativeName / [NativeName] attribute
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("nativeName", NullValueHandling = NullValueHandling.Ignore)]
	public string? NativeName { get; set; }

	/// <summary>
	/// Whether generated by compiler (should be excluded from documentation)
	/// Source: MemberDefinition.IsCompilerGenerated() / [CompilerGenerated] attribute
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isCompilerGenerated", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsCompilerGenerated { get; set; }

	/// <summary>
	/// Whether the property has a getter (properties only)
	/// Source: PropertyDefinition.GetMethod != null
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("hasGetter", NullValueHandling = NullValueHandling.Ignore)]
	public bool? HasGetter { get; set; }

	/// <summary>
	/// Whether the property has a setter (properties only)
	/// Source: PropertyDefinition.SetMethod != null
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("hasSetter", NullValueHandling = NullValueHandling.Ignore)]
	public bool? HasSetter { get; set; }

	/// <summary>
	/// Whether the property has parameters (indexer, properties only)
	/// Source: PropertyDefinition.HasParameters()
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("hasParameters", NullValueHandling = NullValueHandling.Ignore)]
	public bool? HasParameters { get; set; }

	/// <summary>
	/// Whether the field is a constant (fields only)
	/// Source: FieldDefinition.IsLiteral
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isConst", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsConst { get; set; }

	/// <summary>
	/// Whether the field is read-only (fields only)
	/// Source: FieldDefinition.IsInitOnly
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isReadOnly", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsReadOnly { get; set; }

	/// <summary>
	/// Constant value (for const fields)
	/// Source: FieldDefinition.Constant (for IsLiteral fields)
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("constantValue", NullValueHandling = NullValueHandling.Ignore)]
	public object? ConstantValue { get; set; }

	/// <summary>
	/// Number of method parameters (methods/constructors only)
	/// Source: MethodDefinition.Parameters.Count
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("parameterCount", NullValueHandling = NullValueHandling.Ignore)]
	public int? ParameterCount { get; set; }

	/// <summary>
	/// Method parameter details (methods/constructors only)
	/// Source: MethodDefinition.Parameters
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("parameters", NullValueHandling = NullValueHandling.Ignore)]
	public List<ParameterInfo>? Parameters { get; set; }

	/// <summary>
	/// Whether it has [SerializeField] attribute (forces Unity to serialize private fields)
	/// Source: FieldDefinition.CustomAttributes
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("serializeField", NullValueHandling = NullValueHandling.Ignore)]
	public bool? SerializeField { get; set; }

	/// <summary>
	/// Whether it has [HideInInspector] attribute (hides from Unity Inspector)
	/// Source: FieldDefinition.CustomAttributes
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("hideInInspector", NullValueHandling = NullValueHandling.Ignore)]
	public bool? HideInInspector { get; set; }

	/// <summary>
	/// Whether the member is abstract (methods/properties only)
	/// Source: MethodDefinition.IsAbstract
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isAbstract", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsAbstract { get; set; }

	/// <summary>
	/// Whether the method/type is generic
	/// Source: MethodDefinition.HasGenericParameters
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("isGeneric", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsGeneric { get; set; }

	/// <summary>
	/// Number of generic parameters (generic methods only)
	/// Source: MethodDefinition.GenericParameters.Count
	/// Added on 2025-01-20
	/// </summary>
	[JsonProperty("genericParameterCount", NullValueHandling = NullValueHandling.Ignore)]
	public int? GenericParameterCount { get; set; }
}

/// <summary>
/// Method parameter information
/// </summary>
public class ParameterInfo
{
	/// <summary>
	/// Parameter name
	/// Source: ParameterDefinition.Name
	/// </summary>
	[JsonProperty("name")]
	public string Name { get; set; } = string.Empty;

	/// <summary>
	/// Parameter type (fully qualified name)
	/// Source: ParameterDefinition.ParameterType.FullName
	/// </summary>
	[JsonProperty("type")]
	public string Type { get; set; } = string.Empty;

	/// <summary>
	/// Whether the parameter is optional
	/// Source: ParameterDefinition.IsOptional
	/// </summary>
	[JsonProperty("isOptional", NullValueHandling = NullValueHandling.Ignore)]
	public bool? IsOptional { get; set; }

	/// <summary>
	/// Default value of the optional parameter
	/// Source: ParameterDefinition.Constant
	/// </summary>
	[JsonProperty("defaultValue", NullValueHandling = NullValueHandling.Ignore)]
	public object? DefaultValue { get; set; }
}
