using CommandLine;
using CommandLine.Text;

namespace AssetRipper.Tools.AssetDumper.Core;

public class Options
{
	[Option('i', "input", Required = true,
		HelpText = "Input path to Unity game directory")]
	public string InputPath { get; set; } = "";

	[Option('o', "output", Required = false, Default = "./output",
		HelpText = "Output directory for extracted data")]
	public string OutputPath { get; set; } = "./output";

	[Option("collections", Required = false, Default = true,
		HelpText = "Export asset collections (Resources, Addressables, etc.)")]
	public bool ExportCollections { get; set; } = true;

	[Option("facts", Required = false, Default = true,
		HelpText = "Emit facts domain outputs (facts/*.ndjson)")]
	public bool ExportFacts { get; set; } = true;

	[Option("relations", Required = false, Default = true,
		HelpText = "Emit relations domain outputs (relations/*.ndjson)")]
	public bool ExportRelations { get; set; } = true;

	[Option("manifest", Required = false, Default = true,
		HelpText = "Generate manifest.json for the export")]
	public bool ExportManifest { get; set; } = true;

	[Option("indexes", Required = false, Default = true,
		HelpText = "Generate key indexes when available (requires --enable-index)")]
	public bool ExportIndexes { get; set; } = true;

	[Option("metrics", Required = false, Default = false,
		HelpText = "Generate metrics outputs (future use)")]
	public bool ExportMetrics { get; set; }

	[Option("validate-schema", Required = false, Default = false,
		HelpText = "Validate exported NDJSON against Draft 2020-12 JSON Schemas")]
	public bool ValidateSchema { get; set; }

	[Option("scenes", Required = false, Default = true,
		HelpText = "Export scene hierarchy and asset data")]
	public bool ExportScenes { get; set; } = true;

	[Option("script-metadata", Required = false, Default = true,
		HelpText = "Export script metadata facts (facts/script_metadata)")]
	public bool ExportScriptMetadata { get; set; } = true;

	[Option("bundle-metadata", Required = false, Default = true,
		HelpText = "Export bundle metadata facts (facts/bundles)")]
	public bool ExportBundleMetadata { get; set; } = true;

	[Option("assemblies", Required = false, Default = false,
		HelpText = "Export raw assembly DLL files")]
	public bool ExportAssemblies { get; set; } = false;

	[Option('s', "scripts", Required = false, Default = false,
		HelpText = "Export decompiled C# scripts")]
	public bool ExportScripts { get; set; } = false;

	[Option('a', "ast", Required = false, Default = false,
		HelpText = "Generate AST from decompiled scripts")]
	public bool GenerateAst { get; set; } = false;

	[Option('v', "verbose", Required = false, Default = false,
		HelpText = "Enable verbose logging output")]
	public bool Verbose { get; set; }

	[Option("trace-deps", Required = false, Default = false,
		HelpText = "Emit per-asset dependency tracing logs (implies --verbose)")]
	public bool TraceDependencies { get; set; }

	[Option('q', "quiet", Required = false, Default = false,
		HelpText = "Enable silent mode (minimal output)")]
	public bool Silent { get; set; }

	[Option('c', "compact", Required = false, Default = false,
		HelpText = "Generate compact JSON output (no indentation)")]
	public bool CompactJson { get; set; }

	[Option("ignore-nulls", Required = false, Default = true,
		HelpText = "Ignore null values in JSON output")]
	public bool IgnoreNullValues { get; set; } = true;

	[Option("include-metadata", Required = false, Default = false,
		HelpText = "Include additional metadata in asset exports")]
	public bool IncludeAssetMetadata { get; set; }

	[Option("ast-folder", Required = false, Default = "AST",
		HelpText = "Name of folder for AST output")]
	public string AstOutputFolder { get; set; } = "AST";

	[Option("scenes-folder", Required = false, Default = "Scenes",
		HelpText = "Name of folder for scene output")]
	public string ScenesOutputFolder { get; set; } = "Scenes";

	[Option("scene-filter", Required = false,
		HelpText = "Regex pattern to filter scenes to export")]
	public string? SceneFilter { get; set; }

	[Option("assembly-filter", Required = false,
		HelpText = "Regex pattern to filter assemblies for processing")]
	public string? AssemblyFilter { get; set; }

	[Option('e', "exclude", Required = false,
		HelpText = "Regex pattern to exclude files from processing")]
	public string? ExcludePattern { get; set; }

	[Option("skip-auto-generated", Required = false, Default = true,
		HelpText = "Skip auto-generated files (AssemblyInfo.cs, etc.)")]
	public bool SkipAutoGenerated { get; set; } = true;

	[Option("max-file-size", Required = false, Default = 1048576,
		HelpText = "Maximum file size in bytes for processing (0 = unlimited)")]
	public long MaxFileSizeBytes { get; set; } = 1048576;

	[Option("incremental", Required = false, Default = true,
		HelpText = "Skip processing if outputs already exist")]
	public bool IncrementalProcessing { get; set; } = true;

	[Option("sample-rate", Required = false, Default = 1.0,
		HelpText = "Sample rate for processing files (0.1 = 10%, 1.0 = 100%)")]
	public double SampleRate { get; set; } = 1.0;

	[Option("unity-only", Required = false, Default = false,
		HelpText = "Process only Unity project files (skip third-party libraries)")]
	public bool UnityProjectOnly { get; set; } = false;

	[Option("min-lines", Required = false, Default = 3,
		HelpText = "Minimum lines of code to process for AST")]
	public int MinimumLines { get; set; } = 3;

	[Option("preview-only", Required = false, Default = false,
		HelpText = "Preview what would be processed without creating files")]
	public bool PreviewOnly { get; set; } = false;

	[Option("parallel-degree", Required = false, Default = 0,
		HelpText = "Degree of parallelism for processing (0 = auto, 1 = sequential)")]
	public int ParallelDegree { get; set; } = 0;

	[Option("file-timeout", Required = false, Default = 30,
		HelpText = "Timeout in seconds for processing individual files")]
	public int FileTimeoutSeconds { get; set; } = 30;

	[Option("minimal-output", Required = false, Default = false,
		HelpText = "Minimize output size by excluding optional asset reference lists")]
	public bool MinimalOutput { get; set; } = false;

	[Option("enable-index", Required = false, Default = false,
		HelpText = "Generate key index sidecars for fast lookups")]
	public bool EnableIndex { get; set; } = false;

	[Option("shard-size", Required = false, Default = 100000,
		HelpText = "Maximum records per NDJSON shard (0 = unlimited)")]
	public int ShardSize { get; set; } = 100000;

	[Option("compression", Required = false, Default = "none",
		HelpText = "Compression codec: none, gzip, zstd")]
	public string Compression { get; set; } = "none";

	[Option("minimal-deps", Required = false, Default = false,
		HelpText = "Export only cross-collection dependencies (exclude same-collection refs)")]
	public bool MinimalDeps { get; set; } = false;

	[Option("skip-builtin-deps", Required = false, Default = true,
		HelpText = "Skip dependencies to built-in Unity resources")]
	public bool SkipBuiltinDeps { get; set; } = true;

	[Option("skip-self-refs", Required = false, Default = true,
		HelpText = "Skip self-referential dependencies")]
	public bool SkipSelfRefs { get; set; } = true;

	/// <summary>
	/// Apply a configuration preset to simplify common use cases.
	/// </summary>
	public void ApplyPreset(ConfigPreset preset)
	{
		switch (preset)
		{
			case ConfigPreset.Development:
				// Fast iteration for development
				Verbose = true;
				IncrementalProcessing = true;
				ExportMetrics = true;
				ParallelDegree = 0; // Auto
				Compression = "none";
				ValidateSchema = false;
				ExportIndexes = false;
				break;

			case ConfigPreset.Production:
				// Optimized for production exports
				Verbose = false;
				Silent = false;
				IncrementalProcessing = false; // Full export
				ExportMetrics = true;
				ParallelDegree = 0; // Auto
				Compression = "zstd"; // Good compression with speed
				ValidateSchema = true;
				ExportIndexes = true;
				EnableIndex = true;
				CompactJson = true;
				break;

			case ConfigPreset.Debug:
				// Detailed debugging information
				Verbose = true;
				TraceDependencies = true;
				IncrementalProcessing = false;
				ExportMetrics = true;
				ParallelDegree = 1; // Sequential for debugging
				Compression = "none";
				ValidateSchema = true;
				ExportIndexes = true;
				IncludeAssetMetadata = true;
				MinimalOutput = false;
				FileTimeoutSeconds = 120; // Longer timeout
				break;

			case ConfigPreset.Minimal:
				// Minimal output size
				Silent = true;
				ExportMetrics = false;
				ExportScriptMetadata = false;
				ExportBundleMetadata = false;
				ExportScenes = false;
				ExportIndexes = false;
				MinimalOutput = true;
				MinimalDeps = true;
				CompactJson = true;
				Compression = "zstd";
				IgnoreNullValues = true;
				break;

			case ConfigPreset.Analysis:
				// Optimized for static analysis
				ExportScripts = true;
				GenerateAst = true;
				ExportScriptMetadata = true;
				ExportRelations = true;
				ExportMetrics = true;
				ExportIndexes = true;
				EnableIndex = true;
				Verbose = false;
				Silent = false;
				Compression = "gzip"; // Good compatibility
				break;
		}
	}

	/// <summary>
	/// Get a preset configuration by name.
	/// </summary>
	public static Options CreateWithPreset(ConfigPreset preset, string inputPath, string? outputPath = null)
	{
		var options = new Options
		{
			InputPath = inputPath,
			OutputPath = outputPath ?? "./output"
		};
		options.ApplyPreset(preset);
		return options;
	}

	[Usage(ApplicationAlias = "AssetDumper")]
	public static IEnumerable<Example> Examples
	{
		get
		{
			return new List<Example>
			{
				new Example("Basic extraction", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					OutputPath = @"C:\Output"
				}),
				new Example("Fast processing with sampling", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					SampleRate = 0.3,
					UnityProjectOnly = true
				}),
				new Example("Main assembly only", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					AssemblyFilter = "Assembly-CSharp"
				}),
				new Example("Scripts and metadata only", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					ExportScenes = false,
					ExportScriptMetadata = true,
					ExportScripts = true
				}),
				new Example("Preview mode", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					PreviewOnly = true,
					Verbose = true
				}),
				new Example("Silent mode", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					Silent = true
				}),
				new Example("Sequential processing for debugging", new Options {
					InputPath = @"C:\Games\MyUnityGame",
					ParallelDegree = 1,
					FileTimeoutSeconds = 60
				})
			};
		}
	}
}
